name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name f the deployable artifact hashFiles
        type: string
        required: false
        default: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
